on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and deploy
      run: |
        # Build the Docker container
        docker build -t my-react-app .
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker tag my-react-app ${{ secrets.DOCKER_HUB_USERNAME }}/my-react-app:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-react-app:latest
